name: Figure out git-bash on Windows

on: [push, pull_request]



jobs:
  test-git-bash:
    env:
      FLAKY_TESTS: dontcare
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
           python-version: 2.7
      - name: Create paths
        run: |
          mkdir node-v14.0.0-nightly2020-04-08xxxx\out\Release -ea 0
          cd node-v14.0.0-nightly2020-04-08xxxx\out\Release
          dir > listing.txt
          cd ..\..
          echo "::set-env name=TAR_DIR::$pwd"
          echo "Dir is: $pwd"
      - name: debug Copy out directory to checkout dir
        run: |
          dir $env:TAR_DIR\out
          echo "Copying $env:TAR_DIR\out to $env:GITHUB_WORKSPACE\out"
      - name: Copy out directory to checkout dir
        run: |
          Copy-Item -Path "$env:TAR_DIR\out" -Destination "$env:GITHUB_WORKSPACE\out" -Recurse
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Dump path
        run: |
          echo $env:Path
      - name: Try to run parallel/test-child-process-exec-any-shells-windows
        run: |
          node .\test\parallel\test-child-process-exec-any-shells-windows.js