name: Figure out git-bash on Windows

on: [push, pull_request]

env:
  PYTHON_VERSION: 3.8
  FLAKY_TESTS: dontcare

jobs:
  test-git-bash:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Try to run /usr/bin/bash.exe through node        
        run: |
          node .\test\parallel\test-child-process-exec-any-shells-windows.js
        continue-on-error: true
      - name: Make sure git-bash is initialized
        shell: bash
        run: echo bash initialized
        if: always()
        continue-on-error: true
      - name: Try to run /usr/bin/bash.exe through node        
        run: |
          node .\test\parallel\test-child-process-exec-any-shells-windows.js
        if: always()
        continue-on-error: true
